extends: default

rules:
  document-start: {present: false}
  line-length:
    max: 132
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
    ignore: |
      /pipelines/example/example_visit_pipeline.yaml
  truthy:
    # "on" as a key in workflows confuses things
    ignore: |
      /.github/workflows/
      /pipelines/preparation/preparation_matched_jointcal_fgcm.yaml
      /pipelines/preparation/preparation_matched_multi.yaml
      /pipelines/preparation/preparation_matched_multi_jointcal_fgcm.yaml
      /pipelines/preparation/preparation_matched.yaml
  indentation:
    indent-sequences: consistent
