# -*- python -*-
import os

from lsst.sconsUtils import env, scripts

ignoreTests = ["test_ellipKPM.py", "test_photKPM.py", "test_astromKPM.py"]

scripts.BasicSConscript.tests(ignoreList=ignoreTests)
