# This file is part of faro.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# This was generated by running makeDiscreteSkyMap.py on
# a repository produced by running testHsc.sh from validate_drp.
# I then read in the pickled sky map and dumped the config.
# Slight tweaks to the structure were needed.
# This is the result.
config.skyMap["discrete"].patchInnerDimensions=[4000, 4000]
config.skyMap["discrete"].patchBorder=100
config.skyMap["discrete"].tractOverlap=0.0
config.skyMap["discrete"].pixelScale=0.168
config.skyMap["discrete"].projection='TAN'
config.skyMap["discrete"].rotation=0.0
config.skyMap["discrete"].raList=[320.32817849228]
config.skyMap["discrete"].decList=[0.16283948653566044]
config.skyMap["discrete"].radiusList=[1.2774325065269199]
config.skyMap.name = "discrete"
config.name = "discrete/validation_hsc"
