# This was generated by running makeDiscreteSkyMap.py on
# a repository produced by running testHsc.sh from validate_drp.
# I then read in the pickled sky map and dumped the config.
# Slight tweaks to the structure were needed.
# This is the result.
config.skyMap["discrete"].patchInnerDimensions=[4000, 4000]
config.skyMap["discrete"].patchBorder=100
config.skyMap["discrete"].tractOverlap=0.0
config.skyMap["discrete"].pixelScale=0.168
config.skyMap["discrete"].projection='TAN'
config.skyMap["discrete"].rotation=0.0
config.skyMap["discrete"].raList=[320.32817849228]
config.skyMap["discrete"].decList=[0.16283948653566044]
config.skyMap["discrete"].radiusList=[1.2774325065269199]
config.skyMap.name = "discrete"
config.name = "discrete/validation_hsc"
