# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__ = 'unknown'
__repo_version__ = 'unknown'
__fingerprint__ = 'fa77f390874acffab6485f26399a9170f092ca0b *'
__dependency_versions__ = {
}
__all__ = (
    '__version__',
    '__repo_version__',
    '__fingerprint__',
    '__dependency_versions__',
)
